#
# AlpineLinux open jre 8 docker images dockerfile
# @author tekintian
# @url http://github.com/tekintian
# @OPENJDK https://pkgs.alpinelinux.org/contents?branch=edge&name=openjdk8&arch=s390x&repo=community
# @TOMCAT https://wiki.alpinelinux.org/wiki/Tomcat
#

FROM tekintian/alpine:3.8

RUN apk --update add curl wget bash openjdk8 && \
      export JAVA_HOME=$PATH:/usr/lib/jvm/default-jvm && \
      export PATH=${PATH}:${JAVA_HOME}/bin && \
      mkdir -p /usr/local/tomcat &&  cd /usr/local/tomcat && \
      wget http://apache.mirrors.tds.net/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.tar.gz && \
      tar xvzf apache-tomcat-9.0.13.tar.gz && \
      mv apache-tomcat-9.0.13/* /usr/local/tomcat/ && \
      rm -rf apache-tomcat-9.0.13.tar.gz  && \
      apk del wget && \
      rm -rf /var/cache/apk/* 

ENTRYPOINT ["/usr/local/tomcat/bin/catalina.sh","run"]

EXPOSE 8080
VOLUME /usr/local/tomcat/webapps/ROOT
WORKDIR /usr/local/tomcat/webapps